---
- name: deploy synchronisation-s3.deb on the server group (servers_group)
  hosts: servers_group
  become: yes

  tasks:
    - name: install dependencies (python3 and pip)
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: install boto3 via pip
      pip:
        name: boto3
        executable: pip3

    - name: copy the created .deb file to the server
      copy:
        src: syncs3_package.deb
        dest: /tmp/syncs3_package.deb

    - name: install the .deb package
      apt:
        deb: /tmp/syncs3_package.deb
        state: present   